apiVersion: v1
kind: Service
metadata:
  name: 'bookshop-gateway-service'
  namespace: '{{NAMESPACE}}'
spec:
  selector:
    app: 'bookshop-gateway'
  ports:
    - name: http
      protocol: TCP
      port: 5000
