apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-src
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: d-im-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/deploy-im.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}}
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-dev-client -o application-ddd-dev
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-dev --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-api-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-api/DrivewayDemo.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-dev-ace-api -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-acme-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-acme/AcmeV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-dev-ace-acme -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-bernie-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-bernie/BernieV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-dev-ace-bernie -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-chris-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-chris/CrumpledV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-dev, serverconf-ddd, setdbparms-ddd, application-ddd-dev, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-dev-ace-chris -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-dev
      retries: 2
      runAfter:
        - is-cfg-dev
        - wait-im-dev
        - d-api-dev
        - d-acme-dev
        - d-bernie-dev
        - d-chris-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d dev
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-im-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/deploy-im.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -t
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-test
      retries: 2
      runAfter:
        - d-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-test-client -o application-ddd-test
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-test
      retries: 2
      runAfter:
        - d-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-test --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-api-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-api/DrivewayDemo.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-test, serverconf-ddd, setdbparms-ddd, application-ddd-test, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-test-ace-api -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-acme-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-acme/AcmeV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-test, serverconf-ddd, setdbparms-ddd, application-ddd-test, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-test-ace-acme -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-bernie-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-bernie/BernieV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-test, serverconf-ddd, setdbparms-ddd, application-ddd-test, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-test-ace-bernie -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-chris-test
      retries: 2
      runAfter:
        - test-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BAR_FILES='["'${FORKED_REPO%.*}/raw/${BRANCH}/DrivewayDentDeletion/Bar_files/ace-chris/CrumpledV1.bar'"]'
            CONFIGURATIONS="[keystore-ddd, policyproject-ddd-test, serverconf-ddd, setdbparms-ddd, application-ddd-test, barauth-empty]"
            /workspace/git-source/products/bash/release-ace-integration-runtime.sh -n {{NAMESPACE}} -r ddd-test-ace-chris -b "${BAR_FILES}" -c "${CONFIGURATIONS}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-test
      retries: 2
      runAfter:
        - is-cfg-test
        - wait-im-test
        - d-api-test
        - d-acme-test
        - d-bernie-test
        - d-chris-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d test
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: test-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-event-listener
    weight: null
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: test-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: test-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
