apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-apic-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-src
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: d-im-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BASE_URL=${FORKED_REPO%.*}/raw/${BRANCH}
            DDD_ENV='dev'
            /workspace/git-source/DrivewayDentDeletion/Operators/deploy-im.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -e ${DDD_ENV} -u "${BASE_URL}"
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-dev-client -o application-eei
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-dev --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: apic-dev
      retries: 2
      runAfter:
        - wait-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            TARGET_URL="https://ddd-dev-ace-api-ir.{{NAMESPACE}}.svc.cluster.local:7843"
            /workspace/git-source/products/bash/pub-sub-apic.sh -n {{NAMESPACE}} -r ademo -e dev -t ${TARGET_URL}
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-apic-dev
      retries: 2
      runAfter:
        - apic-dev
        - is-cfg-dev
        - wait-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d dev -a
      workspaces:
        - name: git-source
          workspace: git-source

    - name: d-im-test
      retries: 2
      runAfter:
        - test-apic-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            BASE_URL="'${FORKED_REPO%.*}/raw/${BRANCH}'"
            DDD_ENV='test'
            /workspace/git-source/DrivewayDentDeletion/Operators/deploy-im.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -e "${DDD_ENV}" -u "${BASE_URL}" -t
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-test
      retries: 2
      runAfter:
        - d-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-test-client -o application-ddd-test
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-test
      retries: 2
      runAfter:
        - d-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-test --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: apic-test
      retries: 2
      runAfter:
        - wait-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            TARGET_URL="https://ddd-test-ace-api-ir.{{NAMESPACE}}.svc.cluster.local:7843"
            /workspace/git-source/products/bash/pub-sub-apic.sh -n {{NAMESPACE}} -r ademo -e test -t ${TARGET_URL}
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-apic-test
      retries: 2
      runAfter:
        - apic-test
        - is-cfg-test
        - wait-im-test
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d test -a
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: test-apic-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: test-apic-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: test-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-test-apic-event-listener
    weight: null
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-apic-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: test-apic-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: test-apic-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
