apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-pipeline
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
  workspaces:
    - name: git-source
  tasks:
    - name: clone-git-src
      retries: 2
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: "{{FORKED_REPO}}"
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
        - name: revision
          value: "{{BRANCH}}"
      workspaces:
        - name: output
          workspace: git-source

    - name: d-im-dev
      retries: 2
      runAfter:
        - clone-git-src
      taskRef:
        name: run-command
      params:
        - name: command
          value: |
            FORKED_REPO={{FORKED_REPO}}
            BRANCH={{BRANCH}}
            /workspace/git-source/DrivewayDentDeletion/Operators/deploy-im.sh -n {{NAMESPACE}} -b {{DEFAULT_BLOCK_STORAGE}} -f {{DEFAULT_FILE_STORAGE}} -r {FORKED_REPO} -a {BRANCH}
      workspaces:
        - name: git-source
          workspace: git-source

    - name: is-cfg-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/products/bash/create-ace-mq-configuration.sh -n {{NAMESPACE}} -c qm-mq-ddd-qm-dev-client -o application-ddd-dev
      workspaces:
        - name: git-source
          workspace: git-source

    - name: wait-im-dev
      retries: 2
      runAfter:
        - d-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: oc wait --for=condition=ready -n {{NAMESPACE}} IntegrationAssembly ddd-dev --timeout 10m
      workspaces:
        - name: git-source
          workspace: git-source

    - name: test-dev
      retries: 2
      runAfter:
        - is-cfg-dev
        - wait-im-dev
      taskRef:
        name: run-command
      params:
        - name: command
          value: /workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s ddd -d dev
      workspaces:
        - name: git-source
          workspace: git-source
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-event-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - template:
        ref: dev-triggertemplate

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: dev-event-listener
  name: el-main-trigger-route
spec:
  host: ""
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-dev-event-listener
    weight: null
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: dev-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: dev-pipeline
        serviceAccountName: pipeline
        workspaces:
          - name: git-source
            persistentvolumeclaim:
              claimName: git-source-workspace
        params:
          - name: imageTag
            value: $(uid)
        timeout: "20m"
