apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-source-workspace
spec:
  storageClassName: "{{DEFAULT_FILE_STORAGE}}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
