kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-role
rules:
# Permissions for every EventListener deployment to function
- apiGroups: ["triggers.tekton.dev"]
  resources: ["eventlisteners", "triggerbindings", "triggertemplates"]
  verbs: ["get"]
- apiGroups: [""]
# secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
  resources: ["configmaps", "secrets", "serviceaccounts"]
  verbs: ["get", "list", "watch"]
# Permissions to create resources in associated TriggerTemplates
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelineresources", "taskruns"]
  verbs: ["create"]
---

# Ace Integration Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ace-int-srv-role
rules:
# Permissions for appconnect integration server
- apiGroups: ["appconnect.ibm.com"]
  resources: ["designerauthorings", "dashboards", "switchservers", "configurations", "integrationservers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]


---

# MQ Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mq-qm-role
rules:
# Permissions for MQ
- apiGroups: ["mq.ibm.com"]
  resources: ["queuemanagers", "queuemanagers/finalizers", "queuemanagers/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods during deploy stage
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]

---

# Role for the test task in the dev namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-for-test-in-dev-namespace
rules:
# Permissions for test task to list routes in dev namespace
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["list"]
# Permission to get secrets for test script in dev namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---

# Role for the test task in postgres namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-postgres-test-task
  namespace: postgres
rules:
# Permissions for test task to list, get and create pods and configmaps in postgres namespace
- apiGroups: [""]
  resources: ["pods", "pods/exec", "configmaps"]
  verbs: ["list", "get", "create"]

---

# Deploy to test namespace permissions for tekton
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-deploy-test
rules:
# Permission to get tasks, pipelines in tekton.dev in dev namespace - to apply pipeline and task yamls
- apiGroups: ["tekton.dev"]
  resources: ["pipelines", "tasks"]
  verbs: ["get", "create", "patch"]

---

# Deploy mq to test namespace permissions
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-deploy-mq-in-test-namespace
  namespace: "{{NAMESPACE}}-ddd-test"
rules:
# Permission to get tasks, pipelines in tekton.dev in dev namespace - to apply pipeline and task yamls
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
# Permissions for MQ deploy in test namespace
- apiGroups: ["mq.ibm.com"]
  resources: ["queuemanagers", "queuemanagers/finalizers", "queuemanagers/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---

# Deploy ace to test namespace permissions
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-deploy-ace-in-test-namespace
  namespace: "{{NAMESPACE}}-ddd-test"
rules:
# Permission to get tasks, pipelines in tekton.dev in dev namespace - to apply pipeline and task yamls
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
# Permissions for appconnect integration server deployment in test namespace
- apiGroups: ["appconnect.ibm.com"]
  resources: ["designerauthorings", "dashboards", "switchservers", "configurations", "integrationservers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]

---

# Role for the test task to get routes in dev namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-test-routes-in-test-namespace
  namespace: "{{NAMESPACE}}-ddd-test"
rules:
# Permissions for test task to list routes in dev namespace
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["list"]
# Permission to get secrets for test script in test namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---

# Role to get configmaps for test script in dev namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-get-configmap-in-dev-namespace
rules:
# Permission to get configmaps for test script in dev namespace
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

---
# Role for the test task to get routes in dev namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-configure-apic-in-dev-namespace
  namespace: "{{NAMESPACE}}"
rules:
# Permissions for test task to list routes in dev namespace
- apiGroups: ["route.openshift.io"]
  resources: ["routes"]
  verbs: ["get", "list"]
# Permission to get secrets for test script in test namespace
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
