apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-pipeline
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}
# er-pull-secret used to pull images from ER in Dockerfiles

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-test

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-mq-sa
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-push-to-test
secrets:
  - name: cicd-{{NAMESPACE}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-sa
secrets:
  - name: er-pull-secret
  - name: cicd-{{NAMESPACE}}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deploy-to-test

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-mq-deploy-in-test-sa

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-ace-deploy-in-test-sa

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-api-e2e-in-test-sa

---
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-configure-apic-resource-in-dev-sa
