apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-mq
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-api
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-acme
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-bernie
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-chris
spec:
  storageClassName: "{{DEFAULT_BLOCK_STORAGE}}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
