apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: test-apic-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: test-apic-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: test-apic-pipeline
        serviceAccountName: pipeline
        params:
          - name: imageTag
            value: $(uid)
