apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-triggertemplate
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: dev-pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: dev-pipeline
        serviceAccountName: pipeline
        params:
          - name: imageTag
            value: $(uid)
