# Ace Integration Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ace-int-srv-role
rules:
# Permissions for appconnect integration server
- apiGroups: ["appconnect.ibm.com"]
  resources: ["designerauthorings", "dashboards", "switchservers", "configurations", "integrationservers"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods during deploy stage
- apiGroups: [""]
  resources: ["pods", "pods/exec", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["list", "get", "create", "delete"]


---

# MQ Service account configuration
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mq-qm-role
rules:
# Permissions for MQ
- apiGroups: ["mq.ibm.com"]
  resources: ["queuemanagers", "queuemanagers/finalizers", "queuemanagers/status"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
# Permission to get pods during deploy stage
- apiGroups: [""]
  resources: ["pods", "pods/exec", "configmaps", "secrets", "serviceaccounts"]
  verbs: ["list", "get", "create", "delete"]
