swagger: '2.0'
info:
  title: EventEnabledInsurance
  version: 1.0.0
  description: EventEnabledInsurance
  x-ibm-name: eventenabledinsurance
paths:
  /quote:
    get:
      operationId: getQuote
      responses:
        '200':
          description: The operation was successful.
          schema:
            $ref: '#/definitions/Quote'
      produces:
        - application/json
      parameters:
        - name: QuoteID
          in: query
          type: string
          required: true
    post:
      operationId: postQuote
      responses:
        '200':
          description: The operation was successful.
          schema:
            $ref: '#/definitions/Quote'
      consumes:
        - application/json
      produces:
        - application/json
      description: Insert a quote
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Quote'
          description: The request body for the operation
          required: true
basePath: /eventinsurance
definitions:
  Quote:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      age:
        type: integer
      address:
        type: string
      usState:
        type: string
      licensePlate:
        type: string
      descriptionOfDamage:
        type: string
    required:
      - name
      - email
      - age
      - address
      - usState
      - licensePlate
      - descriptionOfDamage
host: $(catalog.host)
schemes:
  - https
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  properties:
    target-url:
      value: >-
        {{TARGET_URL}}
      description: The URL of the target service
      encoded: false
  assembly:
    execute:
      - invoke:
          title: invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)$(request.path)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: blacklist
            values: []
          header-control:
            type: blacklist
            values:
              - ^X-IBM-Client-Id$
          inject-proxy-headers: true
          username: {{BASIC_AUTH_USERNAME}}
          password: {{BASIC_AUTH_PASSWORD}}
  type: rest
  phase: realized
  enforced: true
  testable: true
  application-authentication:
    certificate: false
securityDefinitions:
  clientID:
    type: apiKey
    name: X-IBM-Client-Id
    in: header
security:
  - clientID: []
