apiVersion: v1
kind: Service
metadata:
  name: '{{LANGUAGE}}books-service'
  namespace: '{{NAMESPACE}}'
spec:
  selector:
    app: '{{LANGUAGE}}books-microservice'
  ports:
    - name: http
      protocol: TCP
      port: 5000
