apiVersion: v1
kind: Service
metadata:
  name: customer-order-service
  namespace: '{{NAMESPACE}}'
spec:
  selector:
    app: customer-order-microservice
  ports:
    - name: http
      protocol: TCP
      port: 5000
