apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-source-workspace
spec:
  storageClassName: ibmc-file-gold-gid
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-mq
spec:
  storageClassName: cp4i-block-performance
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-api
spec:
  storageClassName: cp4i-block-performance
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-acme
spec:
  storageClassName: cp4i-block-performance
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-bernie
spec:
  storageClassName: cp4i-block-performance
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildah-ace-chris
spec:
  storageClassName: cp4i-block-performance
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
