# this task is to push the images that our tested to test namespace
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-push-to-test
spec:
  params:
    - name: imageTag
      type: string
      description: The image tag
    - name: imageName
      type: string
      description: The image tag
    - name: pvc
      type: string
      description: The PVC to use for layers
    - name: commandImagePath
      type: string
      description: The full path of the demos command image
      default: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/demos-command:latest
  steps:
    - name: pull-retag-push-to-test
      image: $(params.commandImagePath)
      script: |
        oc tag -n {{NAMESPACE}} $(params.imageName):$(params.imageTag) $(params.imageName):$(params.imageTag)-test

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: api-test-e2e
spec:
  params:
    - name: suffix
      type: string
      description: The suffix for the user and database name
    - name: dddType
      type: string
      description: The ddd demo type
    - name: commandImagePath
      type: string
      description: The full path of the demos command image
      default: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/demos-command:latest
  steps:
    - name: oc
      image: $(params.commandImagePath)
      script: "/image-workspace/git-source/DrivewayDentDeletion/Operators/test-api-e2e.sh -n {{NAMESPACE}} -s $(params.suffix) -d $(params.dddType)"
